/* AUTO-GENERATED by sync-engine next. Do not edit. */
import { syncServer } from "../../../../utils/syncServer";

export const runtime = "nodejs";

export async function POST(request: Request): Promise<Response> {
  return syncServer.push(request);
}
