/* AUTO-GENERATED by sync-engine generator. Do not edit. */
import { randomUUID } from 'crypto';
import { columnList, getEnv, hasColumn, json, err, parseJsonField, validateColumns, validateData, validatePartial } from '../_shared';

const TABLE = "operations";
const schema: Record<string, string> = {
  "id": "TEXT",
  "entity": "TEXT",
  "op_type": "TEXT",
  "payload": "TEXT",
  "created_at": "INTEGER",
  "processed": "INTEGER",
  "attempts": "INTEGER",
  "last_error": "TEXT",
  "client_id": "TEXT",
  "client_op_id": "TEXT",
  "sent_at": "INTEGER",
  "undone": "INTEGER",
  "instance_id": "TEXT"
};
const ALLOWED_COLUMNS: string[] = ["id","entity","op_type","payload","created_at","processed","attempts","last_error","client_id","client_op_id","sent_at","undone","instance_id"];

export async function GET(request: Request) {
  const env = getEnv();
  const url = new URL(request.url);
  const selectParam = url.searchParams.get("select") || "";
  const selectFields = selectParam.split(",").map((s) => s.trim()).filter(Boolean);
  const selectValidation = validateColumns(ALLOWED_COLUMNS, selectFields);
  if (!selectValidation.ok) return err(selectValidation.error ?? "Invalid select field");
  const columns = selectFields.length ? columnList(selectFields) : "*";

  const sinceParam = url.searchParams.get("since");
  const limitParam = url.searchParams.get("limit");
  const instanceId = url.searchParams.get("instance_id");
  const clientId = url.searchParams.get("client_id");

  const where: string[] = [];
  const bindings: unknown[] = [];

  if (sinceParam !== null) {
    const sinceNum = Number(sinceParam);
    if (!Number.isFinite(sinceNum)) return err("Invalid 'since' parameter");
    where.push("created_at > ?");
    bindings.push(sinceNum);
  }
  if (instanceId !== null) {
    where.push("instance_id = ?");
    bindings.push(instanceId);
  }
  if (clientId !== null) {
    where.push("client_id = ?");
    bindings.push(clientId);
  }

  const orderBy = "created_at ASC, id ASC";
  let limitSql = "";
  if (limitParam) {
    const limit = Number(limitParam);
    if (!Number.isInteger(limit) || limit < 1) return err("Invalid 'limit' parameter");
    limitSql = ` LIMIT ${Math.min(limit, 1000)}`;
  }

  const sql = `SELECT ${columns} FROM ${TABLE}` + (where.length ? ` WHERE ${where.join(" AND ")}` : "") + ` ORDER BY ${orderBy}` + limitSql;
  const { results } = await env.DB.prepare(sql).bind(...bindings).all();
  return json((results || []).map((row: Record<string, unknown>) => parseJsonField(row, "payload")));
}

export async function POST(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data: Record<string, unknown>; client_id: string; client_op_id: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const v = validateData(data as Record<string, unknown>, schema);
  if (!v.ok) return err(v.error ?? "Validation error");

  const { results: tableInfo } = await env.DB.prepare(`PRAGMA table_info(${TABLE})`).all();
  const existingCols = new Set<string>((tableInfo || []).map((r: any) => r.name));
  const allColumns = Object.keys(data as Record<string, unknown>);
  const columns = allColumns.filter((c) => existingCols.has(c));
  const missingColumns = allColumns.filter((c) => !existingCols.has(c));
  if (missingColumns.length) {
    console.warn(`Inserting into ${TABLE}: skipping unknown columns: ${missingColumns.join(", ")}`);
  }
  if (columns.some((c) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(c))) return err("Invalid field name");

  const placeholders = columns.map(() => "?").join(", ");
  const sql = `INSERT INTO ${TABLE} (${columns.join(", ")}) VALUES (${placeholders})`;
  const bindings = columns.map((c) => {
    const v = (data as any)[c];
    return v !== null && typeof v === "object" ? JSON.stringify(v) : v;
  });

  if (columns.length === 0) return err("No valid columns to insert for table", 400);

  const stmts = [env.DB.prepare(sql).bind(...bindings)];
  const payloadInsert = JSON.stringify(data);
  const opIdValue = randomUUID();

  stmts.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'insert', ?, ?, ?, ?, 0, ?)`)
    .bind(opIdValue, TABLE, payloadInsert, client_id ?? null, client_op_id ?? null, Date.now(), (data as any).id !== undefined ? String((data as any).id) : null));

  try {
    await env.DB.batch(stmts);
  } catch (e) {
    console.error('DB batch error:', e);
    return err(String(e), 500);
  }

  let result = null;
  if ((data as any).id !== undefined) {
    result = await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).bind((data as any).id).first();
  } else {
    result = (await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE rowid = last_insert_rowid()`).first()) || null;
  }

  return json(result || {}, 201);
}

export async function PUT(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data?: Record<string, unknown>; client_id?: string; client_op_id?: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const id = (data as any).id;
  if (id === undefined || (typeof id !== "string" && typeof id !== "number")) return err("Missing or invalid id in data");

  const v = validatePartial(data as Record<string, unknown>, schema);
  if (!v.ok) return err(v.error ?? "Validation error");

  const updates = Object.keys(data as Record<string, unknown>).filter((k) => k !== "id");
  if (updates.length === 0) return err("No valid fields to update");
  if (updates.some((c) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(c))) return err("Invalid field name");
  const updateValidation = validateColumns(ALLOWED_COLUMNS, updates);
  if (!updateValidation.ok) return err(updateValidation.error ?? "Invalid field name");

  const setClauses = updates.map((c) => `${columnList([c])} = ?`);
  const bindings = updates.map((c) => {
    const v = (data as any)[c];
    if (v === null) return null;
    if (typeof v === "object") return JSON.stringify(v);
    return v;
  });
  if (hasColumn(ALLOWED_COLUMNS, "updated_at") && !updates.includes("updated_at")) {
    setClauses.push(`${columnList(["updated_at"])} = ?`);
    bindings.push(Date.now());
  }

  const sql = `UPDATE ${TABLE} SET ${setClauses.join(", ")} WHERE id = ?`;
  bindings.push(id as unknown);

  const stmtsUpd = [env.DB.prepare(sql).bind(...bindings)];
  const payloadUpdate = JSON.stringify(updates.reduce((acc: Record<string, unknown>, k) => { acc[k] = (data as any)[k]; return acc; }, { id }));

  const lastOp = await env.DB.prepare(`SELECT id, payload FROM operations WHERE entity = ? AND instance_id = ? AND client_id = ? AND op_type = 'update' ORDER BY created_at DESC, id DESC LIMIT 1`)
    .bind(TABLE, String(id), client_id)
    .first();

  let compactSuccess = false;
  if (lastOp && lastOp.payload) {
    try {
      const oldPayload = JSON.parse(lastOp.payload);
      const newPayload = JSON.parse(payloadUpdate);
      const oldChanges = oldPayload.action === "update" && oldPayload.changes && typeof oldPayload.changes === "object"
        ? oldPayload.changes
        : oldPayload;
      const mergedPayload = JSON.stringify({ ...oldChanges, ...newPayload, id });

      stmtsUpd.push(env.DB.prepare(`UPDATE operations SET payload = ?, created_at = ? WHERE id = ?`).bind(mergedPayload, Date.now(), lastOp.id));
      compactSuccess = true;
    } catch (e) {
      console.warn("Failed to compact operation", e);
    }
  }

  if (!compactSuccess) {
    const opIdValueUpd = randomUUID();

    stmtsUpd.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'update', ?, ?, ?, ?, 0, ?)`).bind(opIdValueUpd, TABLE, payloadUpdate, client_id ?? null, client_op_id ?? null, Date.now(), String(id)));
  }

  await env.DB.batch(stmtsUpd);

  const result = await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).bind(id).first();
  return json(result || {});
}

export async function DELETE(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { id?: unknown; client_id?: string; client_op_id?: string } | null;
  let id = body?.id;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  if (id === undefined) {
    const url = new URL(request.url);
    const idParam = url.searchParams.get("id");
    if (idParam !== null) id = Number(idParam);
  }

  if (id === undefined || id === null) return err("Missing or invalid id");

  const stmtsDel = [env.DB.prepare(`DELETE FROM ${TABLE} WHERE id = ?`).bind(id)];
  const payloadDelete = JSON.stringify({ id });
  const opIdValueDel = randomUUID();
  stmtsDel.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'delete', ?, ?, ?, ?, 0, ?)`).bind(opIdValueDel, TABLE, payloadDelete, client_id ?? null, client_op_id ?? null, Date.now(), String(id)));
  await env.DB.batch(stmtsDel);

  return json({ success: true });
}
