/* AUTO-GENERATED by sync-engine generator. Do not edit. */
import { createRepo } from '@mintcd/sync-engine';

export const finalConfig = {
  swPath: "/sw.sync.js"
};

type Schema = {
  "documents": {
    "id": string;
    "source_key": string;
    "source_type": string;
    "source_url": string | null;
    "file_name": string;
    "title": string;
    "created_at": string;
    "updated_at": string;
    "number_of_annotations": number | null;
  };
  "annotations": {
    "id": string;
    "document_id": string;
    "page_index": number;
    "text": string;
    "created_at": string;
    "updated_at": string;
    "color": string;
    "comment": string | null;
    "position": Record<string, unknown>;
  };
  "operations": {
    "id": string;
    "entity": string;
    "op_type": string;
    "payload": string | null;
    "created_at": string;
    "processed": number;
    "attempts": number;
    "last_error": string | null;
    "client_id": string | null;
    "client_op_id": string | null;
    "sent_at": string | null;
    "undone": number;
    "instance_id": string | null;
  };
};
type PrimaryKeys = {
  "documents": "id";
  "annotations": "id";
  "operations": "id";
};
export const db = createRepo<Schema, PrimaryKeys>();