/* AUTO-GENERATED by sync-engine next. Do not edit. */
import {
  defineGeneratedNextSyncConfig,
} from "@mintcd/sync-engine/next";
import type {
  InferDatabase,
} from "@mintcd/sync-engine/schema";

export const finalConfig = defineGeneratedNextSyncConfig({
  "formatVersion": 1,
  "databaseName": "pdf-annotation-db",
  "endpoints": {
    "pull": "/api/sync/pull",
    "push": "/api/sync/push"
  },
  "schema": {
    "formatVersion": 1,
    "tables": {
      "annotations": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "document_id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "page_index": {
            "affinity": "integer",
            "nullable": false,
            "generated": false
          },
          "text": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "color": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "comment": {
            "affinity": "text",
            "nullable": true,
            "generated": false
          },
          "position": {
            "affinity": "numeric",
            "nullable": false,
            "generated": false
          }
        }
      },
      "documents": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "source_key": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "source_type": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "source_url": {
            "affinity": "text",
            "nullable": true,
            "generated": false
          },
          "file_name": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "title": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "number_of_annotations": {
            "affinity": "integer",
            "nullable": true,
            "generated": false
          }
        }
      }
    },
    "schemaHash": "sha256:a6dde84d8af2a55e36b4d2d2a3cdc1365719567cde2e77906917ba10acb09670"
  }
} as const);

export const replicaSchema = finalConfig.schema;
export type Database = InferDatabase<typeof replicaSchema>;
export type TableName = keyof Database;
export type Row<Table extends TableName> = Database[Table];
