/* AUTO-GENERATED by sync-engine generator. Do not edit. */
import { randomUUID } from 'crypto';
import { columnList, getEnv, hasColumn, json, err, parseJsonFields, validateColumns, validateData, validatePartial } from '../_shared';

// --- Configuration ---
const TABLE = "documents";
const schema = {
  "id": "TEXT",
  "source_key": "TEXT",
  "source_type": "TEXT",
  "source_url": "TEXT",
  "file_name": "TEXT",
  "title": "TEXT",
  "created_at": "TEXT",
  "updated_at": "TEXT",
  "number_of_annotations": "INTEGER"
};
const ALLOWED_COLUMNS: string[] = ["id","source_key","source_type","source_url","file_name","title","created_at","updated_at","number_of_annotations"];
const PK = "id";

async function findExistingInsert(
  env: any,
  clientId: string,
  clientOpId: string,
): Promise<Record<string, unknown> | null> {
  const operation = await env.DB.prepare(
    `SELECT instance_id FROM operations WHERE client_id = ? AND client_op_id = ? AND entity = ? AND op_type = 'insert' LIMIT 1`,
  ).bind(clientId, clientOpId, TABLE).first() as { instance_id?: unknown } | null;
  if (operation?.instance_id === undefined || operation.instance_id === null) return null;

  const row = await env.DB.prepare(
    `SELECT * FROM ${TABLE} WHERE ${columnList([PK])} = ?`,
  ).bind(operation.instance_id).first() as Record<string, unknown> | null;
  return row ? parseJsonFields(row, schema) : null;
}

export async function GET(request: Request) {
  const env = getEnv();
  const url = new URL(request.url);

  const selectParam = url.searchParams.get("select") || "";
  const selectFields = selectParam.split(",").map((s) => s.trim()).filter(Boolean);
  const selectValidation = validateColumns(ALLOWED_COLUMNS, selectFields);
  if (!selectValidation.ok) return err(selectValidation.error ?? "Invalid select field");
  const columns = selectFields.length ? columnList(selectFields) : "*";

  const where: string[] = [];
  const bindings: unknown[] = [];
  for (const [key, value] of url.searchParams) {
    if (key === "select") continue;
    if (!hasColumn(ALLOWED_COLUMNS, key)) return err(`Unknown field: ${key}`);
    const column = columnList([key]);
    if (value === "null") {
      where.push(`${column} IS NULL`);
    } else {
      where.push(`${column} = ?`);
      bindings.push(value);
    }
  }

  const sql = `SELECT ${columns} FROM ${TABLE}` + (where.length ? ` WHERE ${where.join(" AND ")}` : "");
  const { results } = await env.DB.prepare(sql).bind(...bindings).all();
  return json((results || []).map((row: Record<string, unknown>) => parseJsonFields(row, schema)));
}

export async function POST(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data: Record<string, unknown>; client_id: string; client_op_id: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;

  const now = Math.floor(Date.now() / 1000);
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const v = validateData(data as Record<string, unknown>, schema);
  if (!v.ok) return err(v.error ?? "Validation error");

  const pkValue = (data as any)[PK];
  if (pkValue === undefined || pkValue === null) {
    return err(`Missing client-generated primary key "${PK}"`);
  }

  const columns = Object.keys(data as Record<string, unknown>);
  const columnValidation = validateColumns(ALLOWED_COLUMNS, columns);
  if (!columnValidation.ok) return err(columnValidation.error ?? "Invalid field name");
  if (columns.length === 0) return err("No valid columns to insert");

  const existing = await findExistingInsert(env, client_id, client_op_id);
  if (existing) return json({ data: existing, client_op_id });

  const placeholders = columns.map(() => "?").join(", ");
  const sql = `INSERT INTO ${TABLE} (${columnList(columns)}) VALUES (${placeholders})`;
  const bindings = columns.map((c) => {
    const v = (data as any)[c];
    return v !== null && typeof v === "object" ? JSON.stringify(v) : v;
  });

  const stmts = [env.DB.prepare(sql).bind(...bindings)];
  const payloadInsert = JSON.stringify(data);

  const opIdValue = randomUUID(); // Generate a unique operation ID for this insert operation

  stmts.push(
    env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'insert', ?, ?, ?, ?, 0, ?)`)
      .bind(opIdValue, TABLE, payloadInsert, client_id, client_op_id, now, String(pkValue))
  );

  try {
    await env.DB.batch(stmts);
  } catch (e) {
    const replay = await findExistingInsert(env, client_id, client_op_id);
    if (replay) return json({ data: replay, client_op_id });
    console.error('DB batch error:', e);
    return err(String(e), 500);
  }

  const result = await env.DB.prepare(
    `SELECT * FROM ${TABLE} WHERE ${columnList([PK])} = ?`,
  ).bind(pkValue).first() as Record<string, unknown> | null;

  return json({ data: result ? parseJsonFields(result, schema) : {}, client_op_id }, 201);
}

export async function PUT(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data?: Record<string, unknown>; client_id?: string; client_op_id?: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;

  const now = Math.floor(Date.now() / 1000);
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const id = (data as any)[PK];
  if (id === undefined || (typeof id !== "string" && typeof id !== "number")) return err(`Missing or invalid ${PK} in data`);

  const v = validatePartial(data as Record<string, unknown>, schema);
  if (!v.ok) return err(v.error ?? "Validation error");

  const updates = Object.keys(data as Record<string, unknown>).filter((k) => k !== PK);
  if (updates.length === 0) return err("No valid fields to update");
  const updateValidation = validateColumns(ALLOWED_COLUMNS, updates);
  if (!updateValidation.ok) return err(updateValidation.error ?? "Invalid field name");

  const setClauses = updates.map((c) => `${columnList([c])} = ?`);
  const bindings = updates.map((c) => {
    const v = (data as any)[c];
    if (v === null) return null;
    if (typeof v === "object") return JSON.stringify(v);
    return v;
  });
  if (hasColumn(ALLOWED_COLUMNS, "updated_at") && !updates.includes("updated_at")) {
    setClauses.push(`${columnList(["updated_at"])} = ?`);
    bindings.push(now);
  }

  const sql = `UPDATE ${TABLE} SET ${setClauses.join(", ")} WHERE ${columnList([PK])} = ?`;
  bindings.push(id as unknown);

  const stmtsUpd = [env.DB.prepare(sql).bind(...bindings)];
  const payloadUpdate = JSON.stringify(updates.reduce((acc: Record<string, unknown>, k) => { acc[k] = (data as any)[k]; return acc; }, { [PK]: id }));

  const lastOp = await env.DB.prepare(`SELECT id, payload FROM operations WHERE entity = ? AND instance_id = ? AND client_id = ? AND op_type = 'update' ORDER BY created_at DESC, id DESC LIMIT 1`)
    .bind(TABLE, String(id), client_id)
    .first();

  let compactSuccess = false;
  if (lastOp && lastOp.payload) {
    try {
      const oldPayload = JSON.parse(lastOp.payload);
      const newPayload = JSON.parse(payloadUpdate);
      const oldChanges = oldPayload.action === "update" && oldPayload.changes && typeof oldPayload.changes === "object"
        ? oldPayload.changes
        : oldPayload;
      const mergedPayload = JSON.stringify({ ...oldChanges, ...newPayload, [PK]: id });

      // Use a conditional update to avoid race conditions
      stmtsUpd.push(env.DB.prepare(`UPDATE operations SET payload = ?, created_at = ? WHERE id = ? AND payload = ?`).bind(mergedPayload, now, lastOp.id, lastOp.payload));
      compactSuccess = true;
    } catch (e) {
      console.warn("Failed to compact operation", e);
    }
  }

  if (!compactSuccess) {
    const opIdValueUpd = randomUUID();
    stmtsUpd.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'update', ?, ?, ?, ?, 0, ?)`).bind(opIdValueUpd, TABLE, payloadUpdate, client_id ?? null, client_op_id ?? null, now, String(id)));
  }

  await env.DB.batch(stmtsUpd);

  const result = await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE ${columnList([PK])} = ?`).bind(id).first();
  return json(result || {});
}

export async function DELETE(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { id?: unknown; client_id?: string; client_op_id?: string } | null;
  let id = body?.id;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");
  const now = Math.floor(Date.now() / 1000);

  if (id === undefined) {
    const url = new URL(request.url);
    const idParam = url.searchParams.get("id");
    if (idParam !== null) id = idParam; // Removed Number() cast to support TEXT PKs
  }

  if (id === undefined || id === null) return err("Missing or invalid id");

  const stmtsDel = [env.DB.prepare(`DELETE FROM ${TABLE} WHERE ${columnList([PK])} = ?`).bind(id)];
  const payloadDelete = JSON.stringify({ [PK]: id });

  const opIdValueDel = randomUUID();
  stmtsDel.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'delete', ?, ?, ?, ?, 0, ?)`).bind(opIdValueDel, TABLE, payloadDelete, client_id ?? null, client_op_id ?? null, now, String(id)));

  await env.DB.batch(stmtsDel);

  return json({ success: true });
}
